{
"레바그안키" : "https://bongzreal.github.io/레바콘/레바그안키.png",
"레바꺄륵" : "https://bongzreal.github.io/레바콘/레바꺄륵.png",
"레바띠용" : "https://bongzreal.github.io/레바콘/레바띠용.png",
"레바모르겠다" : "https://bongzreal.github.io/레바콘/레바모르겠다.png",
"레바불안" : "https://bongzreal.github.io/레바콘/레바불안.png",
"레바설명" : "https://bongzreal.github.io/레바콘/레바설명.png",
"레바어쩌라고" : "https://bongzreal.github.io/레바콘/레바어쩌라고.png",
"레바언행불일치" : "https://bongzreal.github.io/레바콘/레바언행불일치.png",
"레바와아" : "https://bongzreal.github.io/레바콘/레바와아.png",
"레바이제볼만" : "https://bongzreal.github.io/레바콘/레바이제볼만.png",
"레바제일미친" : "https://bongzreal.github.io/레바콘/레바제일미친.png",
"레바쾅쾅쾅" : "https://bongzreal.github.io/레바콘/레바쾅쾅쾅.png",
"레바쾌락" : "https://bongzreal.github.io/레바콘/레바쾌락.jpg",
"레바탕탕" : "https://bongzreal.github.io/레바콘/레바탕탕.gif",
"레바팝콘" : "https://bongzreal.github.io/레바콘/레바팝콘.png",
"레바팝콘2" : "https://bongzreal.github.io/레바콘/레바팝콘2.png",
"레바한참부족" : "https://bongzreal.github.io/레바콘/레바한참부족.png",
"레바핥짝" : "https://bongzreal.github.io/레바콘/레바핥짝.png",
"우리핵드럼" : "https://bongzreal.github.io/우리핵콘/우리핵드럼.gif",
"우리핵박수" : "https://bongzreal.github.io/우리핵콘/우리핵박수.gif",
"우리핵박수2" : "https://bongzreal.github.io/우리핵콘/우리핵박수2.gif",
"우리핵박수3" : "https://bongzreal.github.io/우리핵콘/우리핵박수3.gif",
"우리핵빵야" : "https://bongzreal.github.io/우리핵콘/우리핵빵야.gif",
"우리핵쌍안경" : "https://bongzreal.github.io/우리핵콘/우리핵쌍안경.gif",
"우리핵아닌데" : "https://bongzreal.github.io/우리핵콘/우리핵아닌데.gif",
"우리핵안녕" : "https://bongzreal.github.io/우리핵콘/우리핵안녕.gif",
"우리핵투정" : "https://bongzreal.github.io/우리핵콘/우리핵투정.gif",
"무궁화" : "https://bongzreal.github.io/펄럭콘/무궁화.gif",
"펄럭1" : "https://bongzreal.github.io/펄럭콘/펄럭1.png",
"펄럭2" : "https://bongzreal.github.io/펄럭콘/펄럭2.png",
"펄럭3" : "https://bongzreal.github.io/펄럭콘/펄럭3.png",
"펄럭4" : "https://bongzreal.github.io/펄럭콘/펄럭4.png",

}
