{

"우리가남이가" 		: "http://puu.sh/sYI6B/332770e954.png",
"우리가남이가2" 	: "http://puu.sh/uUSNQ/af6fa6a53b.png",
"갸아악" 			: "http://puu.sh/sYI8U/c8534d3362.png",
"갸아악2" 		: "http://puu.sh/uUSPe/956f235054.png",
"구와아악" 		: "http://puu.sh/sYI9f/5a78970912.png",


"노예일해" 		: "http://puu.sh/sYHwg/b975e5c2bb.png",
"파산" 			: "http://puu.sh/sYHwV/987bcfaa49.png",
"폴짝" 			: "http://puu.sh/sYHzS/6258de0c59.png",

"아아" 			: "http://puu.sh/sYHOI/87b5f5a35f.png",
"마치" 			: "http://puu.sh/sYHUA/6d17506f26.png",
"우리핵안녕" 		: "http://puu.sh/z0zWi/f3933ee907.gif",
"우리핵아닌데" 		: "http://puu.sh/z0zXa/b3b31d3237.gif",
"우리핵박수" 		: "http://puu.sh/z0zXk/6a77f02de4.gif",
"우리핵박수2" 		: "http://puu.sh/z0zXv/585034e422.gif",
"우리핵박수3" 		: "http://puu.sh/z0zXH/66933a5a10.gif",
"우리핵드럼"		: "http://puu.sh/wgfg4/c7cbe33ddf.gif",
"우리핵빵야"		: "http://puu.sh/wgfi1/c5d6eb049f.gif",
"우리핵투정"		: "http://puu.sh/wgfiI/86ff533345.gif",
"우리핵쌍안경"		: "http://puu.sh/wgfjZ/6532603509.gif",
"우리핵확대"		:"http://puu.sh/BFl6b/e962ef0681.gif",
"리듬스탈"	:"http://puu.sh/BFllU/03beb3f195.gif",	

"핫산발상" 		: "http://puu.sh/z0zZo/037402fb12.png",
"핫산펑" 			: "http://puu.sh/uiQ7k/cfeb8148c4.png",
"핫산쾅" 			: "http://puu.sh/uiQ7Y/0ecf16e428.png",


"무지개깃발"		:"http://puu.sh/vPrSf/09c146bd43.gif",
"세종대왕"			:"http://puu.sh/vPuG2/7c09f353e4.png",


"인텔"			:"http://puu.sh/z0A5E/59db1ffdb3.png",
"암드"			:"http://puu.sh/vPvvx/26e8bc4afd.png",
"라이젠"			:"http://puu.sh/w6GG4/c209251aab.png",
"리사수"			:"http://puu.sh/z0A7h/cdeb9d62a7.png",
"문풍당당"			:"http://puu.sh/z1ZDe/e4643f3a51.gif",
"문풍당당2"		:"http://puu.sh/z1ZDl/0b6ed9ae2e.gif",
"문풍당당3"		:"http://puu.sh/z1ZDu/5f6e7a50af.gif",
"문풍당당4"		:"http://puu.sh/BFlwY/7f3fa6098c.gif",
"문풍당당5"		:"http://puu.sh/BFlxv/7afb86cd62.gif",
"문풍당당6"		:"http://puu.sh/BFlxN/4be893ff50.gif",


"이풍당당"			:"http://puu.sh/z1ZDz/7ed4e9f877.gif",
"이풍당당2"		:"http://puu.sh/z1ZDM/94b965f434.gif",
"이풍당당3"		:"http://puu.sh/z1ZDR/e1f346def7.gif",
"예풍당당"			:"http://puu.sh/zjcn0/b1be39d32f.gif",
"좋겠다"			:"http://puu.sh/z1ZG8/e13a8f7799.gif",
"네말이맞아"		:"http://puu.sh/z1ZGf/9a8c39da85.gif",
"짱이야"			:"http://puu.sh/z1ZGo/41e421ae33.gif",
"정말멋있다"		:"http://puu.sh/z1ZGu/d120403bec.gif",
"축하해"			:"http://funzinnu.com/stream/cdn/dccon/축하해.gif",



"이지붐"		:"http://puu.sh/wnhAQ/ab32ff9185.jpg",



"레바와아"		:"http://funzinnu.com/stream/cdn/dccon/레바와아.png",
"설명들갑"		:"http://funzinnu.com/stream/cdn/dccon/설명들갑.png",	
"레바띠용"		:"http://funzinnu.com/stream/cdn/dccon/레바띠용.png",	
"에라모겠"		:"http://funzinnu.com/stream/cdn/dccon/에라모겠.png",	
"그안키"		:"http://funzinnu.com/stream/cdn/dccon/그안키.png",		
"이제좀볼만"	:"http://funzinnu.com/stream/cdn/dccon/이제좀볼만.png",
"레바탕탕"		:"http://puu.sh/z1ZHA/79a7dd985c.gif",
"팝콘레바"		:"http://funzinnu.com/stream/cdn/dccon/팝콘레바.png",	
"레바팝콘"		:"http://funzinnu.com/stream/cdn/dccon/레바팝콘.png",	

"매우정상"		:"http://funzinnu.com/stream/cdn/dccon/매우정상.png",	
"댕댕콘" 			: "http://puu.sh/sYGXR/d303c80b91.gif",
"펄럭" 			: "http://puu.sh/sYHmC/b4392cd1ff.gif",
"펄럭2" 			: "http://puu.sh/uCzS2/5ce60d4025.gif",
"태극기" 			: "http://puu.sh/uCzU9/12427373db.png",
"무궁화" 			: "http://puu.sh/uCzVT/4d0ed10beb.png",
"무궁화2" 		: "http://puu.sh/uCzXm/183c2f630d.png",
"김치워리어" 		: "http://puu.sh/uCB7y/a14d2a4d0f.png",


"토드흐뭇"		:"http://funzinnu.com/stream/cdn/dccon/토드흐뭇.png",
"토드불만"		:"http://funzinnu.com/stream/cdn/dccon/토드불만.png",
"토드분노"		:"http://funzinnu.com/stream/cdn/dccon/토드분노.png",
"토드끄덕"		:"http://puu.sh/BiUgN/2f3b0dee31.gif",
"토드만족"		:"http://puu.sh/BiUiv/11afb5f9c0.gif",
"게이븐"		:"http://funzinnu.com/stream/cdn/dccon/게이븐.png",

"눈물너클즈"	:"http://funzinnu.com/stream/cdn/dccon/눈물너클즈.png",
"눈물소닉"		:"http://funzinnu.com/stream/cdn/dccon/눈물소닉.png",
"눈물에이미"	:"http://funzinnu.com/stream/cdn/dccon/눈물에이미.png",
"눈물테일즈"	:"http://funzinnu.com/stream/cdn/dccon/눈물테일즈.png",
"소닉붐"		:"http://funzinnu.com/stream/cdn/dccon/소닉붐.png",
"싸닉"		:"http://funzinnu.com/stream/cdn/dccon/싸닉.png",
"골든싸닉"		:"http://funzinnu.com/stream/cdn/dccon/골든싸닉.png",
"따일즈"		:"http://funzinnu.com/stream/cdn/dccon/따일즈.png",
"나클즈"		:"http://funzinnu.com/stream/cdn/dccon/나클즈.png",
"싸도우"		:"http://funzinnu.com/stream/cdn/dccon/싸도우.png",
"리얼싸닉"		:"http://funzinnu.com/stream/cdn/dccon/리얼싸닉.png",
"스웨그싸닉"	:"http://funzinnu.com/stream/cdn/dccon/스웨그싸닉.png",
"싸닉매니아"	:"http://funzinnu.com/stream/cdn/dccon/싸닉매니아.png",



"광클"		:"http://puu.sh/CMxAv/6a5f24025b.gif",
"냥슬픔"		:"http://puu.sh/CMxAD/0160c2920c.gif",
"식은땀"		:"http://puu.sh/CMxAO/940caaf499.gif",
"골목놀람"	:"http://puu.sh/CMxAU/a0810388e8.jpg",
"표지판"		:"http://puu.sh/CMxB4/460ea5db85.gif",
"냥경악"		:"http://puu.sh/ADjCO/25da447f93.gif",
"냥경악2"	:"http://puu.sh/CMxBl/28f8e39647.gif",
"냥경악3"	:"http://funzinnu.com/stream/cdn/dccon/냥경악3.gif",
"냥정색"		:"http://puu.sh/CMxBq/bb11f4a8e1.gif",
"냥확대"		:"http://funzinnu.com/stream/cdn/dccon/냥확대.gif",
"굳건이"		:"http://puu.sh/CMxBt/4067d8496d.jpg",
"하수구토"	:"http://puu.sh/CMxBI/92dd739d00.jpg",
"말도안돼"	:"http://puu.sh/CMxB9/e1c6d9b138.jpg",





"4딸라"		:"http://funzinnu.com/stream/cdn/dccon/사딸라.png",
"오케이땡큐"	:"http://funzinnu.com/stream/cdn/dccon/오케이땡큐.png",
"상하이조"		:"http://puu.sh/z0AjH/5d5930dae8.gif",
"심영박수"		:"http://puu.sh/z0AjR/8a31abb602.gif",
"심영박수2"	:"http://puu.sh/z0Ak2/6d458cc569.gif",
"연막"		:"http://puu.sh/z0Ak7/6dfe193df0.gif",
"폭발"		:"http://puu.sh/z0Akc/58afe661c1.gif",
"폭발그루트"	:"http://puu.sh/ADj88/4ba85ee9f7.gif",
"핫산끝"		:"http://puu.sh/z1ZOF/f7ef5cf3ad.png",
"페페흐음"		:"http://puu.sh/z1ZOP/e64486ddfb.png",
"페페발암"		:"http://puu.sh/z1ZOY/ce1c31e0af.png",
"페페따봉"		:"http://puu.sh/z1ZP9/e569382de4.png",
"페바"		:"http://puu.sh/z1Zyi/6ae6a9c81a.gif",
"화난페페"		:"http://puu.sh/z1ZPj/c1683d5767.png",
"앵그리페페"	:"http://puu.sh/z1ZPq/747d2f7208.png",
"앵그리페페2"		:"http://puu.sh/Be2Hx/9f648cfbdd.png",
"페페허"		:"http://puu.sh/z1ZPB/d994be3467.png",
"페페헉"		:"http://puu.sh/z1ZPF/e0d7b61b35.png",
"페페헐"		:"http://puu.sh/z1ZPN/58337b396d.png",
"페페기대"		:"http://puu.sh/zjcpV/cdc1cd72ce.png",
"페페봉기"		:"http://puu.sh/zjcrh/d0a1b39ca9.png",
"페페물음표"	:"http://puu.sh/zjcrH/0112c6cd8d.png",
"페페빼액"		:"http://puu.sh/zjcst/a1490e87b0.png",
"페페우울"		:"http://puu.sh/zjcsK/d371bcf126.png",
"페페멋짐"		:"http://puu.sh/zjcsU/fb1ef383f6.png",
"페페자살"		:"http://puu.sh/zjctp/bbef0ca176.png",
"페페놀람"		:"http://puu.sh/ADiUj/091e312d18.png",
"페페띠용"		:"http://puu.sh/ADiVq/1e0a8305d7.png",
"페페모자"		:"http://puu.sh/Be2tD/f36fcdc016.png",
"페페초딩"		:"http://puu.sh/Be2ve/3c2d26f556.png",
"페페팝콘"		:"http://puu.sh/Be2DW/f93c58d6d5.gif",
"페페VR"			:"http://puu.sh/Be2Ed/e9e07b2a3d.png",
"페페박수"		:"http://funzinnu.com/stream/cdn/dccon/페페박수.gif",
"페페예스"		:"http://funzinnu.com/stream/cdn/dccon/페페예스.png",
"페페노"			:"http://funzinnu.com/stream/cdn/dccon/페페노.png",
"페페경악"		:"http://funzinnu.com/stream/cdn/dccon/페페경악.jpg",
"페페댄스"		:"http://funzinnu.com/stream/cdn/dccon/페페댄스.gif",
"뚜와뚜"		:"http://puu.sh/Be2Ah/45bf2b9f0e.gif",
"치킨"		:"http://puu.sh/Be2Co/be012eeca0.gif",


"입체팝콘"		:"http://puu.sh/BFlr5/326b6ea808.gif",
"누물보"		:"http://funzinnu.com/stream/cdn/dccon/누물보.png",
"정신승리"		:"http://funzinnu.com/stream/cdn/dccon/정신승리.png",
"희키박수"		:"http://puu.sh/z1ZAF/8db9f67c73.gif",
"핑구박수"	:"http://puu.sh/BUnTK/cd463b7397.gif",
"럼프따봉"	:"http://puu.sh/zTXWW/eae2153360.png",
"럼프끄덕"	:"http://puu.sh/zTXWd/2e332bb9f1.gif",
"럼프리듬"	:"http://puu.sh/ADjTZ/e42da8f95f.gif",
"럼프박수"		:"http://funzinnu.com/stream/cdn/dccon/럼프박수.gif",
"트로피카나"	:"http://puu.sh/z0Apn/eee5b378b1.gif",
"트로피카나2"	:"http://puu.sh/z0Apu/5d5a863b6d.gif",
"ppa카나"		:"http://puu.sh/z0AeV/528222e2bb.gif",
"ppap"		:"http://puu.sh/z0AoC/0b91e18d04.gif",
"불편"		:"http://puu.sh/z1ZJo/9e02fd493a.png",
"편안"		:"http://puu.sh/z1ZJg/97080873fd.png",

"구린갑"		:"http://puu.sh/z0AnT/a0b2f338f0.gif",
"버크흐뭇"		:"http://puu.sh/z0Ao1/c1d39266ec.gif",
"팬빡침"		:"http://puu.sh/z0Aoc/4700cd442b.gif",

"맥댄스"		:"http://puu.sh/Aq8vJ/92dd04d250.gif",
"맥박수"		:"http://puu.sh/Aq8ue/9af5312f64.gif",
"맥풍당당"		:"http://puu.sh/Aq8rF/d7aa5e4607.gif",
"맥놀람"		:"http://puu.sh/Aq8uU/03b9f60053.gif",
"맥절정"		:"http://puu.sh/BhS49/16881c31db.gif",
"맥환호"		:"http://puu.sh/BhS28/d1068a51f0.gif",

"존슨끄덕"		:"http://puu.sh/Aq6vS/cf276cee6f.gif",
"갓탤띠용"		:"http://puu.sh/Aq6xH/1fcddb30ad.gif",
"y"		:"http://funzinnu.com/stream/cdn/dccon/y.jpg",

"덥덥따봉"		:"http://puu.sh/BhRZL/e70f6f504b.gif",
"덥덥좌절"		:"http://puu.sh/BhS2Y/45409fb23b.gif",
"덥덥띠용"		:"http://puu.sh/BiTZY/378e2e6680.gif",

"공중제비"		:"http://funzinnu.com/stream/cdn/dccon/공중제비.gif",

"배트눈물"		:"http://puu.sh/Aq6yl/934bbba494.gif",
"배트끄덕"		:"http://puu.sh/Aq6yO/f0e36c36f8.gif",
"토비눈물"		:"http://puu.sh/ADjBG/036d4d3139.gif",

"대현짜잔"	:"http://puu.sh/BvBPU/7909e0cd2a.gif",
"감탄"		:"http://puu.sh/BvCc8/7f1cefad9c.gif",
"발작"		:"http://puu.sh/BvCd0/bd39325632.gif",

"칠레감탄"	:"http://puu.sh/BUnCS/0a0d98bfe5.gif",
"칠레감동"	:"http://puu.sh/BUnBv/bb485988db.gif",
"칠레점프"	:"http://puu.sh/BUnBJ/2082c18175.gif",
"칠레스고이"	:"http://puu.sh/BUnDw/651798b54a.gif",
"칠레감탄2"	:"http://puu.sh/BUnCk/e50414bbbf.gif",
"칠레감탄3"	:"http://puu.sh/BUnD9/0effe17112.gif",
"칠레감탄4"	:"http://puu.sh/BUnEZ/a492bb59ce.gif",

"다시보니"	:"http://funzinnu.com/stream/cdn/dccon/다시보니.gif",

"f"	:"http://funzinnu.com/stream/cdn/dccon/F.gif",

"제리하이"	:"http://puu.sh/BUnIZ/7f025b1629.gif",
"제리폭소"	:"http://puu.sh/BUnJZ/504b41f780.gif",
"제리할짝"	:"http://funzinnu.com/stream/cdn/dccon/제리할짝.gif",
"제리하트"	:"http://funzinnu.com/stream/cdn/dccon/제리하트.gif",
"톰박수"	:"http://funzinnu.com/stream/cdn/dccon/톰박수.gif",

"올뺌경악"	:"http://puu.sh/BUnM2/3025ce15b5.png",
"올뺌경악2"	:"http://puu.sh/BUnOw/7e886f6a1b.png",
"이글"	:"http://puu.sh/BUnMW/56ba600eed.png",

"개간지"		:"http://funzinnu.com/stream/cdn/dccon/개간지.gif",
"개모찌"		:"http://funzinnu.com/stream/cdn/dccon/개모찌.png",
"개슬픔"		:"http://funzinnu.com/stream/cdn/dccon/개슬픔.png",
"개아련"		:"http://funzinnu.com/stream/cdn/dccon/개아련.png",
"냥구토"		:"http://funzinnu.com/stream/cdn/dccon/냥구토.png",
"돈냄새"		:"http://funzinnu.com/stream/cdn/dccon/돈냄새.gif",
"시즈"		:"http://funzinnu.com/stream/cdn/dccon/시즈.gif",
"유턴"		:"http://funzinnu.com/stream/cdn/dccon/유턴.gif",
"그건니가"		:"http://funzinnu.com/stream/cdn/dccon/그건니가.jpg",



"힘의차이"		:"http://puu.sh/BiU78/df255e1c34.png",
"선생따봉"		:"http://puu.sh/BiUdo/e83fc5980e.png",
"계산중"		:"http://funzinnu.com/stream/cdn/dccon/계산중.jpg",
"할매댄스"		:"http://funzinnu.com/stream/cdn/dccon/할매댄스.gif",

"두근두근"		:"http://puu.sh/z0Ahb/915c092108.gif",

"띠껍"		:"http://funzinnu.com/stream/cdn/dccon/띠껍.png",
"띠껍하트"		:"http://funzinnu.com/stream/cdn/dccon/띠껍하트.png",
"옐로카드"		:"http://funzinnu.com/stream/cdn/dccon/옐로카드.png",
"레드카드"		:"http://funzinnu.com/stream/cdn/dccon/레드카드.png",
"띠껍예스"		:"http://funzinnu.com/stream/cdn/dccon/띠껍예스.png",
"띠껍노"		:"http://funzinnu.com/stream/cdn/dccon/띠껍노.png",
"띠껍따봉"		:"http://funzinnu.com/stream/cdn/dccon/띠껍따봉.png",
"띠껍쌍따봉"	:"http://funzinnu.com/stream/cdn/dccon/띠껍쌍따봉.png",

"흠"			:"http://puu.sh/Be2hh/2052db8c12.png",
"스웩흠"		:"http://puu.sh/Be2kM/454abf3902.png",
"흠흠흠"		:"http://puu.sh/Be2r0/2b8f366a88.png",
"혼란흠"		:"http://puu.sh/Be2pC/c9792a4383.gif",
"회전흠"		:"http://puu.sh/Be2dP/625aaffb00.gif",
"회전흠2"		:"http://puu.sh/Be29N/ba58dff3e6.gif",
"회전흠3"		:"https://puu.sh/Be1Wf/d3c61e2eb4.gif",
"발퀄흠"		:"http://puu.sh/Be21C/156dbd7153.png",
"고퀄흠"		:"http://puu.sh/Be23i/548d77a6d8.png",
"왜곡흠"		:"http://puu.sh/BhSfo/b2e7ab899d.gif",

"라이안따봉"	:"http://puu.sh/BhRU3/11b721faee.png",
"라이안땀"	:"http://puu.sh/BvBBz/a0656c7f94.png",
"어파치띠껍"	:"http://puu.sh/BhRUN/1ca549a934.png",
"어파치안녕"	:"http://puu.sh/BvBx9/6972d84475.png",
"똘람하트"	:"http://puu.sh/BvBCE/d8708482b6.png",
"똘람놀람"	:"http://puu.sh/BvBDp/11c12d5ed0.png",
"똘람홀쭉"	:"http://puu.sh/BvBDN/5144a94129.png",
"똘람뚱뚱"	:"http://puu.sh/BvBEg/e49bf426aa.png",

"퍄"			:"http://puu.sh/BvBKe/99e3da636b.gif",

"만두죽창"		:"http://funzinnu.com/stream/cdn/dccon/만두죽창.png",
"만두눈물"		:"http://puu.sh/Aq6JY/73a85f9cb5.png",
"만두팝콘"		:"http://puu.sh/BvBZT/75b60fa54e.png",
"민트초코"		:"http://puu.sh/z1ZzW/db3f46e4f6.gif",
"민초우유"		:"http://puu.sh/BvCoF/8727b7b102.gif",
"박수시나"		:"http://puu.sh/z1ZA6/f2451e7710.gif",
"혼란시나"		:"http://puu.sh/zTXYv/dd5a16e710.gif",
"축소시나"		:"http://puu.sh/ADiDv/bbde3b8193.gif",
"시나띠용"		:"http://puu.sh/BFl8s/aab43351e5.gif",
"부커띠용"		:"http://puu.sh/BFlan/b213a87b3b.gif",
"에디와우"		:"http://puu.sh/ADiGZ/90a3ec61d9.gif",
"좌절"		:"http://puu.sh/ADjQT/fe32a6241b.gif",
"좌절2"		:"http://puu.sh/ADiKq/1d0cba0206.gif",
"나홀로놀람"	:"http://puu.sh/ADjS3/9f3e74bb28.png",

"스펀지팝콘"	:"http://puu.sh/BFlg5/ba248ac4fa.gif",
"선글띠용"	:"http://puu.sh/BFliI/f4489d24a4.gif",


"배그15배"	:"http://funzinnu.com/stream/cdn/dccon/배그15배.png",
"배그맞워요"	:"http://funzinnu.com/stream/cdn/dccon/배그맞워요.png",
"배그아닌대"	:"http://funzinnu.com/stream/cdn/dccon/배그아닌대.png",
"배그아이구야"	:"http://funzinnu.com/stream/cdn/dccon/배그아이구야.png",

"자기과시"		:"http://puu.sh/vPoBx/876be04ff7.png",
"자기과시2"	:"http://funzinnu.com/stream/cdn/dccon/자기과시.png",

"눈물앵무"		:"http://puu.sh/Aq8o9/9d15460e3b.gif",
"혼란앵무"		:"http://puu.sh/Aq8oK/cc2c218b34.gif",

"콜라"	:"http://puu.sh/BvCgZ/04b77d79d5.png",
"콜라2"		:"http://puu.sh/BvChW/81619336db.png",
"콜라3"		:"http://puu.sh/BvCiA/eb7e1faaad.png",
"콜라4"		:"http://puu.sh/BvCiP/d4d965b8f5.png",

"핫도그"		:"http://puu.sh/BvClu/c0ae0fdd7d.png",
"빛도그"		:"http://puu.sh/BvClF/7f0f3e32b5.gif",

"호랑이"		:"http://puu.sh/wDOdG/13d2d761ce.gif",
"호랑이2"		:"http://puu.sh/wDOe7/36b8368f11.gif",
"호랑이3"		:"http://puu.sh/wDOeJ/e19c56e39d.gif",
"호랑이4"		:"http://puu.sh/wDOfh/04d70d5fa0.gif",

"파누따봉"		:"http://puu.sh/Be3kq/89d46757a6.png",
"파누버럭"		:"http://puu.sh/Be3jk/8d377608f8.png",
"눈물파누"		:"http://puu.sh/Be3k4/2d8aaa4c6d.png",
"파누부끄"		:"http://puu.sh/BhS5Y/b78b4231d4.png",

"서순"		:"http://funzinnu.com/stream/cdn/dccon/서순.png",
"순서"		:"http://funzinnu.com/stream/cdn/dccon/순서.png",

"인공지능"		:"http://funzinnu.com/stream/cdn/dccon/인공지능.jpg",


"짜잔"		:"http://puu.sh/Aq6DB/8669fb7c72.png",
"잔짜잔"		:"http://puu.sh/Aq6E0/5f2d36a3d7.png",
"짜잔2"		:"http://puu.sh/Aq6B4/0c99c88570.gif",
"잔짜잔2"		:"http://puu.sh/Aq6AL/0d026e8330.gif",
"버그"		:"http://puu.sh/Aq6Er/9be1c0f9ad.gif",
"꼬우면"		:"http://puu.sh/Aq6EC/70fe78993d.gif",
"B풍당당"		:"http://puu.sh/Aq6Af/e88febfaab.gif",
"어케이겼노"	:"http://puu.sh/Aq6Cf/b699e9e374.gif",
"어케했노"		:"http://puu.sh/Aq6CD/1426cebd94.gif",

"RGB"		:"http://puu.sh/Aq6IC/ed8555d17a.gif",
"대게"		:"http://puu.sh/zdhyQ/5e8c041bb5.png",

"파킨" 			: "http://puu.sh/sYGmi/b435c89ebe.png",
"우지챠" 			: "http://puu.sh/sYGqp/e69c0e1902.png", 
"고마워미도리" 		: "http://puu.sh/sYGrI/9613db3d21.png",
"팝콘" 			: "http://puu.sh/sYGtJ/6154d80c7d.png",


"볼트넷여친"	:"http://funzinnu.com/stream/cdn/dccon/볼트넷여친.png",	
"볼트넷친구"	:"http://funzinnu.com/stream/cdn/dccon/볼트넷친구.png",	
"볼트동정"		:"http://funzinnu.com/stream/cdn/dccon/볼트동정.png",		
"볼트가정사"	:"http://funzinnu.com/stream/cdn/dccon/볼트가정사.png",	
"볼트등골"		:"http://funzinnu.com/stream/cdn/dccon/볼트등골.png",		
"볼트병신"		:"http://funzinnu.com/stream/cdn/dccon/볼트병신.png",		
"볼트나무"		:"http://funzinnu.com/stream/cdn/dccon/볼트나무.png",		
"볼트대머리"	:"http://funzinnu.com/stream/cdn/dccon/볼트대머리.png",	
"볼트침대"		:"http://funzinnu.com/stream/cdn/dccon/볼트침대.png",		
"볼트활활"		:"http://funzinnu.com/stream/cdn/dccon/볼트활활.png",		
"볼트댕댕"		:"http://funzinnu.com/stream/cdn/dccon/볼트댕댕.png",		
"볼트기계"		:"http://funzinnu.com/stream/cdn/dccon/볼트기계.png",		
"볼트결혼"		:"http://funzinnu.com/stream/cdn/dccon/볼트결혼.png",		
"볼트비밀친구"	:"http://funzinnu.com/stream/cdn/dccon/볼트비밀친구.png",
"볼트군인"		:"http://funzinnu.com/stream/cdn/dccon/볼트군인.png",		
"볼트닌자"		:"http://funzinnu.com/stream/cdn/dccon/볼트닌자.png",		
"볼트인육"		:"http://funzinnu.com/stream/cdn/dccon/볼트인육.png",		
"볼트핫산"		:"http://funzinnu.com/stream/cdn/dccon/볼트핫산.png",		
"볼트주사"		:"http://funzinnu.com/stream/cdn/dccon/볼트주사.png",		
"볼트빼액"		:"http://funzinnu.com/stream/cdn/dccon/볼트빼액.png",		
"볼트꺼져"		:"http://funzinnu.com/stream/cdn/dccon/볼트꺼져.png",		
"볼트닥쳐"		:"http://funzinnu.com/stream/cdn/dccon/볼트닥쳐.png",		
"볼트안마"		:"http://funzinnu.com/stream/cdn/dccon/볼트안마.png",		
"볼트망치"		:"http://funzinnu.com/stream/cdn/dccon/볼트망치.png",		
"볼트빠따"		:"http://funzinnu.com/stream/cdn/dccon/볼트빠따.png",		
"볼트수류탄"	:"http://funzinnu.com/stream/cdn/dccon/볼트수류탄.png",	
"볼트전기톱"	:"http://funzinnu.com/stream/cdn/dccon/볼트전기톱.png",	
"볼트장전"		:"http://funzinnu.com/stream/cdn/dccon/볼트장전.png",		
"볼트저격"		:"http://funzinnu.com/stream/cdn/dccon/볼트저격.png",		
"볼트라이플"	:"http://funzinnu.com/stream/cdn/dccon/볼트라이플.png",	
"볼트화염병"	:"http://funzinnu.com/stream/cdn/dccon/볼트화염병.png",	
"볼트주먹"		:"http://funzinnu.com/stream/cdn/dccon/볼트주먹.png",		
"볼트컴온"		:"http://funzinnu.com/stream/cdn/dccon/볼트컴온.png",		
"볼트투창"		:"http://funzinnu.com/stream/cdn/dccon/볼트투창.png",		
"볼트아킴보"	:"http://funzinnu.com/stream/cdn/dccon/볼트아킴보.png",	
"볼트고인"		:"http://funzinnu.com/stream/cdn/dccon/볼트고인.png",		
"볼트부활"		:"http://funzinnu.com/stream/cdn/dccon/볼트부활.png",		
"볼트띠용"		:"http://funzinnu.com/stream/cdn/dccon/볼트띠용.png",		
"볼트신문"		:"http://funzinnu.com/stream/cdn/dccon/볼트신문.png",		
"볼트눈물"		:"http://funzinnu.com/stream/cdn/dccon/볼트눈물.png",		
"볼트투시"		:"http://funzinnu.com/stream/cdn/dccon/볼트투시.png",		
"볼트토끼"		:"http://funzinnu.com/stream/cdn/dccon/볼트토끼.png",		
"볼트포기"		:"http://funzinnu.com/stream/cdn/dccon/볼트포기.png",		
"볼트자살"		:"http://funzinnu.com/stream/cdn/dccon/볼트자살.png",		
"볼트게이"		:"http://funzinnu.com/stream/cdn/dccon/볼트게이.png",		
"볼트딸딸"		:"http://funzinnu.com/stream/cdn/dccon/볼트딸딸.png",		
"볼트음주"		:"http://funzinnu.com/stream/cdn/dccon/볼트음주.png",		
"볼트수면"		:"http://funzinnu.com/stream/cdn/dccon/볼트수면.png",		
"볼트우승"		:"http://funzinnu.com/stream/cdn/dccon/볼트우승.png",		
"볼트루저"		:"http://funzinnu.com/stream/cdn/dccon/볼트루저.png",		
"볼트구토"		:"http://funzinnu.com/stream/cdn/dccon/볼트구토.png",		
"볼트예수"		:"http://funzinnu.com/stream/cdn/dccon/볼트예수.png",				
"볼트연설"		:"http://funzinnu.com/stream/cdn/dccon/볼트연설.png",		
"볼트공중"		:"http://funzinnu.com/stream/cdn/dccon/볼트공중.png",		
"볼트엄격"		:"http://funzinnu.com/stream/cdn/dccon/볼트엄격.png",		
"볼트진지"		:"http://funzinnu.com/stream/cdn/dccon/볼트진지.png",		
"볼트근엄"		:"http://funzinnu.com/stream/cdn/dccon/볼트근엄.png",		
"볼트펄럭"		:"http://funzinnu.com/stream/cdn/dccon/볼트펄럭.png",		
"볼트답답"		:"http://funzinnu.com/stream/cdn/dccon/볼트답답.png",		
"볼트절망"		:"http://funzinnu.com/stream/cdn/dccon/볼트절망.png",		
"볼트관전"		:"http://funzinnu.com/stream/cdn/dccon/볼트관전.png",		
"볼트통수"		:"http://funzinnu.com/stream/cdn/dccon/볼트통수.png",		
"볼트연주"		:"http://funzinnu.com/stream/cdn/dccon/볼트연주.png",		
"볼트파오후"	:"http://funzinnu.com/stream/cdn/dccon/볼트파오후.png",	
"볼트딴딴"		:"http://funzinnu.com/stream/cdn/dccon/볼트딴딴.png",		
"볼트처형"		:"http://funzinnu.com/stream/cdn/dccon/볼트처형.png",		
"볼트명상"		:"http://funzinnu.com/stream/cdn/dccon/볼트명상.png",		
"볼트마약"		:"http://funzinnu.com/stream/cdn/dccon/볼트마약.png",		
"볼트떠남"		:"http://funzinnu.com/stream/cdn/dccon/볼트떠남.png",		
"볼트경례"		:"http://funzinnu.com/stream/cdn/dccon/볼트경례.png",		
"볼트근육"		:"http://funzinnu.com/stream/cdn/dccon/볼트근육.png",		
"볼트자본"		:"http://funzinnu.com/stream/cdn/dccon/볼트자본.png",
"볼트논리"		:"http://funzinnu.com/stream/cdn/dccon/볼트논리.png",
"볼트따봉"		:"http://funzinnu.com/stream/cdn/dccon/볼트따봉.png",
"볼트찡긋"		:"http://funzinnu.com/stream/cdn/dccon/볼트찡긋.png",
"볼트불만"		:"http://funzinnu.com/stream/cdn/dccon/볼트불만.png",
"볼트검"			:"http://funzinnu.com/stream/cdn/dccon/볼트검.png",
"볼트기상"		:"http://funzinnu.com/stream/cdn/dccon/볼트기상.png",
"볼트독서"		:"http://funzinnu.com/stream/cdn/dccon/볼트독서.png",
"볼트전구"		:"http://funzinnu.com/stream/cdn/dccon/볼트전구.png",
"볼트천재"		:"http://funzinnu.com/stream/cdn/dccon/볼트천재.png",


"문따봉"		:"http://puu.sh/zTXPH/f95d1a0c7b.png",
"문팝콘"		:"http://funzinnu.com/stream/cdn/dccon/문팝콘.png",
"문초롱"		:"http://puu.sh/zTXQ5/145a2d418c.png",
"문저주"		:"http://puu.sh/zTXP5/0f570bd24c.png",
"문쿨쿨"		:"http://puu.sh/zTXQJ/274ec19459.png",
"문노래"		:"http://puu.sh/zTXRa/249785e085.png",
"문헐"		:"http://puu.sh/zTXRJ/88ac779786.png",
"문구토"		:"http://puu.sh/zTXSl/c27acc3ff0.png",
"문깔깔"		:"http://puu.sh/zTXSL/ca0b735c88.png",
"ㄱ-"		:"http://puu.sh/zTXTh/42f453f137.png",


"눈물한조" 		: "http://puu.sh/t8AzS/ed3902b020.png",
"눈물파라" 		: "http://puu.sh/t8AAl/4f88234e1b.png",
"눈물트레" 		: "http://puu.sh/t8AAM/9e700a7c58.png",
"눈물토르" 		: "http://puu.sh/t8AB3/bd4e7abc7b.png",
"눈물젠야타" 		: "http://puu.sh/t8ABp/fb09b2415b.png",
"눈물정크랫" 		: "http://puu.sh/t8ACu/2a389b7037.png",
"눈물자리야" 		: "http://puu.sh/t8ADn/4f1e8c4348.png",
"눈물윈스턴" 		: "http://puu.sh/t8ADU/1f59655255.png",
"눈물위도우" 		: "http://puu.sh/t8AEe/8943fd7f5f.png",
"눈물시메" 		: "http://puu.sh/t8AEx/16059a62e7.png",
"눈물디바" 		: "http://puu.sh/t8AEL/33aefce68b.png",
"눈물리퍼" 		: "http://puu.sh/t8AFr/88961a767a.png",
"눈물바스" 		: "http://puu.sh/t8AGe/531aed5ad2.png",
"눈물루시우" 		: "http://puu.sh/t8AGA/7554ab714e.png",
"눈물맥크리" 		: "http://puu.sh/t8AGT/fb3b0f180c.png",
"눈물메르시" 		: "http://puu.sh/t8AH2/b02a70e14c.png",
"눈물메이" 		: "http://puu.sh/t8AHm/4fa63e5f57.png",
"눈물겐지" 		: "http://puu.sh/t8AHA/564f6cd96c.png",
"눈물로드" 		: "http://puu.sh/t8AHQ/f8052672ab.png",
"눈물라인" 		: "http://puu.sh/t8AIJ/e71bf1f812.png",
"눈물솔져" 		: "http://puu.sh/t8AIU/5fa525dd2b.png",

"화남" 			: "http://puu.sh/sYK8a/24d3b6f131.gif",
"멀미1" 			: "http://puu.sh/sYK9C/a10d2071eb.gif",
"멀미2" 			: "http://puu.sh/sYKa6/cb919c6ee3.gif",
"멀미3" 			: "http://puu.sh/sYKat/04740c5901.gif",
"피곤" 			: "http://puu.sh/sYKpE/0bda56935c.gif",
"행복2" 			: "http://puu.sh/sYKtg/aba9eddc15.gif",
"행복1" 			: "http://puu.sh/sYKvq/1649710517.gif",
"무표정" 			: "http://puu.sh/sYKuX/21fa12f183.gif",
"불행1" 			: "http://puu.sh/sYKvH/82f0f1e3e9.gif",
"불행2" 			: "http://puu.sh/sYKw6/fbc34c8d47.gif",
"림발진" 			: "http://puu.sh/uiTma/a09dfd7d0f.png",
"기가" 			: "http://puu.sh/uiTpj/491c151f2d.png",
"나선" 			: "http://puu.sh/uiTra/a85428de8e.png",
"레이다운" 		: "http://puu.sh/uiTtM/02a1763d61.png",
"루핑" 			: "http://puu.sh/uiTuH/aba611159e.png",
"리버서" 			: "http://puu.sh/uiTyR/ccf2d031b4.png",
"마인" 			: "http://puu.sh/uiTCe/efefacbaa3.png",
"탄광" 			: "http://puu.sh/uiTER/bb9ace72b1.png",
"멀티디멘션" 		: "http://puu.sh/uiTH9/ba4309134e.png",
"미니" 			: "http://puu.sh/uiTIF/8d7fd5151c.png",
"미니서스펜디드" 	: "http://puu.sh/uiTP1/91f84b6c9f.png",
"버지니아" 		: "http://puu.sh/uiTQV/90a670e18b.png",
"봅슬레이" 		: "http://puu.sh/uiTS8/6a613d0f4e.png",
"플라잉턴" 		: "http://puu.sh/uiUQk/5ab3098806.png",
"사이드프릭션" 		: "http://puu.sh/uiTV8/510a541f1b.png",
"서스펜디드" 		: "http://puu.sh/uiTXy/508d789275.png",
"수직낙하" 		: "http://puu.sh/uiU3e/e96a3896a0.png",
"스탠드업" 		: "http://puu.sh/uiU5o/75ea63caee.png",
"스티플체이스" 		: "http://puu.sh/uiU6B/78f207c35c.png",
"트위스터" 		: "http://puu.sh/uiUa1/2d1cafc29a.png",
"플로어리스" 		: "http://puu.sh/uiUaO/b6b8554965.png",
"스파이럴" 		: "http://puu.sh/uiUdb/5015ea7e02.png",
"에어파워드버티컬" 	: "http://puu.sh/uiUfP/d2e563a53d.png",
"역방향자유낙하" 	: "http://puu.sh/uiUhQ/21ef24e2db.png",
"리버스프리폴" 		: "http://puu.sh/uiUhQ/21ef24e2db.png",
"와일드마우스" 		: "http://puu.sh/uiUlQ/2e83eace9c.png",
"우든트위스터" 		: "http://puu.sh/uiUn7/e0515ae5a8.png",
"우든" 			: "http://puu.sh/uiUp4/c33a337347.png",
"우든와일드" 		: "http://puu.sh/uiUtc/d766f78a21.png",
"우든와일드광산" 	: "http://puu.sh/uiUsn/0a50590870.png",
"워터코스터" 		: "http://puu.sh/uiUuG/4c467a4451.png",
"인버티드" 		: "http://puu.sh/uiUy7/efe37d478f.png",
"주니어" 			: "http://puu.sh/uiUAY/2be643349b.png",
"컴팩트인버티드" 	: "http://puu.sh/uiUCq/430c858195.png",
"플라잉" 			: "http://puu.sh/uiUFj/3828ed5f5e.png",
"하트라인" 		: "http://puu.sh/uiT5C/ce1d81312a.gif",

"엘리베이터" 		: "http://puu.sh/uiUSc/57613e8e6b.png",
"모노레일" 		: "http://puu.sh/uiUTq/c4db2027be.png",
"트램" 			: "http://puu.sh/uiUUP/748fefde1a.png",
"전차" 			: "http://puu.sh/uiUUP/748fefde1a.png",
"모형기차" 		: "http://puu.sh/uiUWL/373cf0da9b.png",
"서스펜디드모노레일" 	: "http://puu.sh/uiUXR/291d016d0e.png",
"체어리프트" 		: "http://puu.sh/uiUZn/a04a75f3c8.png",

"유령기차" 		: "http://puu.sh/uiV8n/eec88a1698.png",
"관람차" 			: "http://puu.sh/uiV9r/a920a8ab29.png",
"귀신의집" 		: "http://puu.sh/uiVah/da4586cbac.png",
"미끄럼틀" 		: "http://puu.sh/uiVbq/4ca676446f.png",
"자전거" 			: "http://puu.sh/uiVdL/b4ff4789b8.png",
"골프" 			: "http://puu.sh/uiVg4/2ce8f81559.png",
"미니헬리곱터" 		: "http://puu.sh/uiVnx/0e984e5e62.png",
"메이즈" 			: "http://puu.sh/uiVoo/33b1f9dc7b.png",
"범퍼카" 			: "http://puu.sh/uiVq4/3529458411.png",
"비행접시" 		: "http://puu.sh/uiVtA/3d42d14591.png",
"서커스" 			: "http://puu.sh/uiVuv/33f275ddbc.png",
"스페이스링" 		: "http://puu.sh/uiVwg/62ae4e5e39.png",
"삐뚤어진집" 		: "http://puu.sh/uiVxA/d3029ec2b5.png",
"전망탑" 			: "http://puu.sh/uiVAs/96265bc749.png",
"2층전망탑" 		: "http://puu.sh/uiVBf/d50b98a900.png",
"카라이드" 		: "http://puu.sh/uiVHg/6bb04339c0.png",
"떼껄룩카라이드" 	: "http://puu.sh/uiVIZ/838901accc.png",
"회전목마" 		: "http://puu.sh/uiVMm/31d4a5f119.png",
"2층회전목마" 		: "http://puu.sh/uiVN5/d4addfcd87.png",
"360도바이킹" 		: "http://puu.sh/uiVSS/50a2a40d9b.png",
"영화관" 			: "http://puu.sh/uiVUl/c8a2fa3e8b.png",
"고카트" 			: "http://puu.sh/uiVWT/711681e19f.png",
"런치드프리폴" 		: "http://puu.sh/uiVXQ/86d3525056.png",
"양탄자" 			: "http://puu.sh/uiVYT/f503845336.png",
"모션시뮬레이터" 	: "http://puu.sh/uiW0f/bbc725d579.png",
"바이킹" 			: "http://puu.sh/uiW3q/19ea28a02b.png",
"엔터프라이즈" 		: "http://puu.sh/uiW4N/42a06e5e3b.png",
"자이로드롭" 		: "http://puu.sh/uiW5R/07d8ef9823.png",
"탑스핀" 			: "http://puu.sh/uiW7J/350f64dbdb.png",
"트위스트" 		: "http://puu.sh/uiWab/262c457e3c.png",
"리버래프트" 		: "http://puu.sh/uiWeR/72017c199b.png",
"리버래피드" 		: "http://puu.sh/uiWfD/2669ee6e1d.png",
"워터슬라이드" 		: "http://puu.sh/uiWnR/8743e9e3ff.png",
"백조보트" 		: "http://puu.sh/uiWoO/613a5e1479.png",
"보트" 			: "http://puu.sh/uiWpG/cd43066f29.png",
"카누" 			: "http://puu.sh/uiWsf/793d5fc295.png",
"스플래시보트" 		: "http://puu.sh/uiWuR/1785260787.png",
"보트라이드" 		: "http://puu.sh/uiWuR/1785260787.png",
"후룸라이드" 		: "http://puu.sh/uiWxt/65e7b5fbf3.png",
"기념품가게" 		: "http://puu.sh/uiWNq/20795e8251.png",
"모자가게" 		: "http://puu.sh/uiWPv/97952f4499.png",
"선글라스가게" 		: "http://puu.sh/uiWQG/180fbf7785.png",
"티셔츠가게" 		: "http://puu.sh/uiWTe/c0a1fbf62c.png",
"풍선가게" 		: "http://puu.sh/uiWU5/809f9c92e3.png",
"안내소" 			: "http://puu.sh/uiWV9/7940ec19bd.png",
"두유가게" 		: "http://puu.sh/uiWWi/b585871363.png",
"레모네이드가게" 	: "http://puu.sh/uiWXY/ea5822021d.png",
"수정과가게" 		: "http://puu.sh/uiX2d/508824c9ac.png",
"스타프루트가게" 	: "http://puu.sh/uiWZR/1e2ab1be61.png",
"아이스티가게" 		: "http://puu.sh/uiXa3/0159324ef8.png",
"음료수가게" 		: "http://puu.sh/uiXba/6f2cb6bfd4.png",
"커피가게" 		: "http://puu.sh/uiXfb/9e2ebccd40.png",
"핫초코가게" 		: "http://puu.sh/uiXgj/a1c19423c5.png",
"감자칩가게" 		: "http://puu.sh/uiXlx/6707cfdaa9.png",
"감자튀김가게" 		: "http://puu.sh/uiXmo/7924d2b234.png",
"고기국수가게" 		: "http://puu.sh/uiXo3/b11196b2c1.png",
"고기완자탕가게" 	: "http://puu.sh/uiXqw/a4d736cc8c.png",
"아이스크림가게" 	: "http://puu.sh/uiXsn/5ca4f90ef4.png",
"소세지가게" 		: "http://puu.sh/uiXuy/1b1b673391.png",
"도넛가게" 		: "http://puu.sh/uiXx7/21e929d26e.png",
"만두국가게" 		: "http://puu.sh/uiXzf/a6812fbbde.png",
"사과사탕가게" 		: "http://puu.sh/uiY6T/fb9c8d8585.png",
"샌드위치가게" 		: "http://puu.sh/uiY9D/cb1e7674be.png",
"솜사탕가게" 		: "http://puu.sh/uiYrD/20fb6d9cba.png",
"아이스크림콘가게" 	: "http://puu.sh/uiYsG/c053e368bd.png",
"치킨너겟가게" 		: "http://puu.sh/uiYtN/a6e762355b.png",
"쿠기가게" 		: "http://puu.sh/uiYvi/d50cf35796.png",
"튀김쌀국수가게" 	: "http://puu.sh/uiYwa/ab86682016.png",
"팝콘가게" 		: "http://puu.sh/uiYyu/aed79302b2.png",
"치킨가게" 		: "http://puu.sh/uiYAa/5ebd56df2d.png",
"프레첼가게" 		: "http://puu.sh/uiYCh/93c4c781df.png",
"피자가게" 		: "http://puu.sh/uiYDt/ae141b960e.png",
"핫도그가게" 		: "http://puu.sh/uiYEn/44324afae1.png",
"촉수가게" 		: "http://puu.sh/uiYHC/f8ea23101e.png",
"햄버거가게" 		: "http://puu.sh/uiYNP/5105052cd7.png",
"케이크가게" 		: "http://puu.sh/uiYOK/9c0b2e3981.png",
"병원" 			: "http://puu.sh/uiYQ4/35375d3ba4.png",
"ATM" 			: "http://puu.sh/uiYRI/c7f8e6401a.png",
"화장실" 			: "http://puu.sh/uiYTP/888f378c54.png"

}
